#DO NOT CHANGE 
#MODIFICATION IT IS POSSIBLE TO DISABLE THE FILE
#PCKGS FEDORA 27 OFFLINE
#OFFLINE INSTALLER
#READ INFO FILE FOR MORE INFORMATION
#VARIABLE ARE DETECTABLE
#IMPORT FROM OS
#IMPORT FROM DACOLOR
#by ebf learn | Soak
fn2ver = "EBF"
ln2ver = "LEARN"

